spring:
  application:
    name: export-service

filesystem:
  tmp-folder: /var/export-service/tmp
  export-folder: /var/export-service/export

scheduling:
  redemption-cron: "0 0 * * * *"  # Every hour
  outpay-cron: "0 0 */6 * * *"     # Every 6 hours
  own-and-ben-cron: "0 0 */12 * * *" # Every 12 hours
